# we need to add the params 

# params:
#     - data_ingestion.test_size

#  params:
#     - feature_engineering.max_features

# params:
#     - model_building.n_estimators
#     - model_building.random_state


data_ingestion: # i.e inside this file we want to adjust this param 
  test_size: 5

feature_engineering:
  max_features: 70

model_building: 
  n_estimators : 15
  random_state : 2